[package]
name = "ray_caster"
version = "0.1.0"
authors = ["jon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.1"
rayon = "1.1"

[profile.release]
opt-level = 3